version: 0.0
os: linux
files:
  - source: deploy/deploy-be.zip
    destination: /home/ec2-user/release
    overwrite: yes
permissions:
  - object: /
    pattern: "**"
    ownenr: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/beforeDeploy.sh
  AfterInstall:
    - location: scripts/deploy.sh
