version: 0.0
os: linux
files:
  - source: deploy/deploy-be.zip
    destination: /home/ec2-user/zip
    overwrite: yes
permissions:
  - object: /
    pattern: "**"
    ownenr: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ec2-user
