spring:
  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop
logging:
  level:
    org.hibernate.SQL: debug

database_url: localhost:3306
database_username: dev
database_password: dev1234
